### ISSUE TITLE
Run aptitude updates

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#11]
Run the following:

* `apt-get update -y`
* `apt-get update -y`
* `apt-get autoremove`

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    server_harden:
        package_update: true
```

Setting `package_update` to `false` will skip this step.
