### ISSUE TITLE
Install and configure fail2ban

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#12]
No configuration required (for now).  May add some capabilities at a later time.

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    server_harden:
        fail2ban: true
```

`fail2ban` can be set to `false` to skip installation.
