### ISSUE TITLE
Add the Deploy user

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#13]
Add the `deploy` user with full sudo access.

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    server_harden:
        users:
            deploy:
                sudo     : true
                password : true
                ssh_keys:
                    - PUB...KEY1
                    - PUB...KEY2
```

If `users` is set to false, user configuration will be skipped.

As many users as needed can be created with the `users` block.  By default, only the `deploy` user will be created, and the script will prompt for that user's password.

The `sudo` option will give the user full sudo access.  Partial sudo is not currently supported.

* `true` to auto-generate a password for the user
* `false` for no password (not recommended)
* A String value to set the password from the script (e.g., from a vault)
* Omitted to prompt the user for a password (default)

`ssh_keys` can either be a string or an array.  Note that if you don't set any SSH keys and password-login is disabled for SSH, a warning will be thrown, but configuration will continue.
