### ISSUE TITLE
Lock down SSH

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#14]
**This should be done last, as is prevents the `root` user from accessing via Ansible**  Ensure documentation provides an example of how to switch to a non-root user mid-playbook.

Set the following two lines in the `/etc/ssh/sshd_config` file:

```
PermitRootLogin no
PasswordAuthentication no
```

Then restart the SSH service with `service ssh restart`

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    server_harden:
        ssh:
            root_login    : false
            password_auth : false
```

If `ssh` is set to `false`, configuration is skipped.
