### ISSUE TITLE
Enable the Firewall

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#15]
Configure UFW to allow ports 22, 80, and 443 by default.

Call `ufw enable` when complete.

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    firewall:
        - 22
        - 80
        - 443
```

`firewall` can be set to `false` to skip firewall configuration.

Firewall takes an array of ports to open on the server.  A warning should be shown if port 22 is not included, but configuration should continue.
