### ISSUE TITLE
Enable LogWatch

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#17]
Install LogWatch with `apt-get install logwatch`

If a mail option is provided, edit `vim /etc/cron.daily/00logwatch` to add this line:

```
/usr/sbin/logwatch --output mail --mailto test@gmail.com --detail high
```

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    logwatch:
        email: # (undefined)
```

If `email` is set (and valid), the line will be added to logwatch to send emails.
