### ISSUE TITLE
Change the user's root password

### ISSUE THREAD

**Issue by andrewvaughan** [andrewvaughan/ansible-role-server-harden#9]
Provide an option to enter the server's root password.

## Variables

The following are the available variables for configuration of this feature, along with their defaults:

```yaml
vars:
    server_harden:
        root:
            password: # (undefined)
            ssh_keys: false
```

If `root` is set to `false`, root user configuration will be skipped.

`password` can be set to the following:

* `true` to auto-generate a root password for the user
* `false` to skip setting the root password
* A String value to set the root password from the script (e.g., from a vault)
* Omitted to prompt the user for a password (default)

`ssh_keys` can be one of the following:

* `false` to remove all SSH keys (default)
* A String to set a single authorized key
* An array to set multiple SSH keys

Note that if you set SSH keys, but root login is disabled for SSH, a warning will be thrown, but configuration will continue.
